// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdzfnoktkadfphxwthrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkemZub2t0a2FkZnBoeHd0aHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDA0NzcsImV4cCI6MjA2MTAxNjQ3N30.08ENuL-y2s9_J9akfFv39ozelot4t9qeV8z5ty9L2Ic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);